org: daveasiamah
app: vanirest
# serverless.yml

service: vanirest

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1

functions:
  # server:
  #   handler: server.handler
  #   events:
  #     - http: ANY /
  #     - http: "ANY {proxy+}"

  getProducts:
    handler: controllers/productController.getProducts
    events:
      - http: "GET /products"

  createProduct:
    handler: controllers/productController.createProduct
    events:
      - http: "POST /products"
